---
# tasks file for all nodes

- name: "Install selinux python library"
  package:
    name: "libselinux-python"
    state: "present"

- name: "Disable SELinux"
  selinux:
    state: "disabled"

- name: "Copy k8s repo"
  copy:
    src: "kubernetes.repo"
    dest: "/etc/yum.repos.d/"

- name: "Install software"
  package:
    name: "{{ item }}"
    state: "present"
  loop: "{{ software }}"

- name: "Copy docker daemon file"
  copy:
    src: "daemon.json"
    dest: "/etc/docker/"

- name: "Copy k8s modules conf file"
  copy:
    src: "modules-load.d_k8s.conf"
    dest: "/etc/modules-load.d/k8s.conf"

- name: "Copy k8s sysctl conf file"
  copy:
    src: "sysctl.d_k8s.conf"
    dest: "/etc/sysctl.d/k8s.conf"

- name: "Enable and start services"
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: "yes"
  loop: "{{ services }}"

- name: "Reload sysctl confs"
  command: "sysctl --system"