---
# tasks file for master node

- name: "Init kubeadm"
  shell: "kubeadm init --pod-network-cidr={{ network_name }} --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
  ignore_errors: yes
  register: init_cmd

- name: "Init kubeadm block"
  block:
    - name: "Configure kubectl - create directory"
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: "Configure kubectl - copy kubectl config file"
      shell: "cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"
      args:
        warn: false
    
    - name: "Configure kubectl - change permissions"
      shell: "chown $(id -u):$(id -g) $HOME/.kube/config"
      args:
        warn: false

    - name: "Download and modify kube-flannel"
      shell: "curl https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml | sed  's@10.244.0.0/16@{{ network_name }}@' > kube-flannel.yml"
      args:
        warn: false

    - name: "Deploy kube-flannel"
      shell: "kubectl apply -f kube-flannel.yml"
      args:
        warn: false
  
  when: init_cmd.rc == 0

- name: "Create token command for worker nodes"
  shell: "kubeadm token create  --print-join-command"
  register: join_cmd
  args:
    warn: false